name: Save Form Submission

on:
  issues:
    types: [opened]

jobs:
  save-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Parse issue body
        id: parse
        run: |
          echo "${{ github.event.issue.body }}" > temp.json
          mkdir -p data
          TIMESTAMP=$(date +%s)
          mv temp.json data/submission-${TIMESTAMP}.json

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/
          git commit -m "Add new submission"
          git push
